### PR TITLE
Fix: use isActive in Africa's Talking notifications

### LINKED ISSUE #902: Properly handle Africa's Talking voice notifications callbacks
Verboice is generating lots of `timeout` errors waiting for Africa's Talking to send it a callback - only the callback has already arrived, but is being mishandled.

```
2022-03-17T09:04:04.668550391Z 09:04:04.668 [info] [<0.25612.18>|25799486] session: Session ("22dacf1b-9a94-4deb-9a9e-ae1bc5e12d95") dial
2022-03-17T09:04:04.798845483Z 09:04:04.798 [info] [<0.25612.18>|25799486] session: Dialing to 256xxxxxxxxx through channel Uganda AfT
2022-03-17T09:04:10.074867770Z 09:04:10.074 [info] [<0.25639.18>|undefined] africas_talking_httpd_module: Receiving callSessionState [{"callSessionState","NotAnswered"},{"hangupCause","SUBSCRIBER_ABSENT"},{"direction","Outbound"},{"callerCountryCode","256"},{"durationInSeconds","0"},{"amount","0"},{"callerNumber","+256xxxxxxxxx"},{"destinationNumber","+256yyyyyyyyyy"},{"callerCarrierName","MTN"},{"status","NotAnswered"},{"sessionId","ATVId_221c9e6c4045a27a3a94e71a49a90b8c"},{"callStartTime","None"},{"isActive","0"},{"currencyCode","UGX"}]
2022-03-17T09:04:10.075767837Z 09:04:10.075 [info] [<0.25612.18>|25799486] session: Session ("22dacf1b-9a94-4deb-9a9e-ae1bc5e12d95") answer
2022-03-17T09:09:10.162577085Z 09:09:10.160 [info] [<0.25612.18>|25799486] session: Call failed with reason {internal_error,{timeout,{gen_server,call,[<0.25640.18>,{capture,{url,"https://surveda-africa.org/audio/c291e180-xxxx-yyyy-zzzz-aaaaaaaaaaaa.mp3"},5,[],1,1},300000]}}}
2022-03-17T09:09:10.170162250Z 09:09:10.161 [warning] [<0.25612.18>|25799486] session: Session ("22dacf1b-9a94-4deb-9a9e-ae1bc5e12d95") terminated with reason: {timeout,{gen_server,call,[<0.25640.18>,{capture,{url,"https://surveda-africa.org/audio/c291e180-xxxx-yyyy-zzzz-aaaaaaaaaaaa.mp3"},5,[],1,1},300000]}}
```

The call in Verboice is this one: https://verboice.surveda-africa.org/calls/548

See https://developers.africastalking.com/docs/voice/notifications for AfT's official docs.
See #894 for the previous issue, and #895 for an incomplete attempt to fix it.

### PR DESCRIPTION
**Pull request by ysbaddaden**
This should hopefully fix the session state issues we're having with Africa's Talking channels.

fixes #902

### CODE REVIEW

**Comment by ysbaddaden** [comment]
Part of it is true: the erlang docker image is based on Debian Jessie which only ships Ruby 2.1 but the `activesupport` gem requires Ruby 1.8.7 not Ruby 2.2 :confused:

**Comment by ysbaddaden** [comment]
Now the problem is that the Erlang dependencies use the unauthenticated `git://` protocol that GitHub removed support for some months ago. This is a simple fix: just replace `git://` with `https://`, and we can fix the direct dependencies, as well as indirect dependencies from instedd, but we're powerless with other dependencies, who do use the `git://` protocol!

**Comment by matiasgarciaisaia** [comment]
I'm [publishing a preview image](https://github.com/instedd/verboice/actions/runs/2103593802) so we can actually test this in the relevant Surveda environment.

**Comment by matiasgarciaisaia** [comment]
I've just [tried a call that yielded "No answer"](https://verboice.surveda-africa.org/calls/1017), and it was correctly marked as finished in Verboice.

We'll run a couple of tests soon, and I'll try to review the code while we're on that.

**Review by matiasgarciaisaia — APPROVED** [review]
PR is short & sweet 👌

Let's wait a couple of days to see how the tests go before merging.

Not sure I'd merge it into `fix/docker-image-build`, though - I'd merge #905 independently of this, won't you?

**Comment by ysbaddaden** [comment]
@matiasgarciaisaia GitHub automatically changes the base branch: merge #905 first and this PR will be changed to target `main`.

**Comment by matiasgarciaisaia** [comment]
Well, I had to not only manually update the base branch, but also rebase it manually 😅 

It may have to do with the fact that I've squash-merged #905 instead of doing a git merge - idk.

I'll merge this since it looks OK and it's strictly better than what we already have - which is broken.

**Pull request merged**
