### PR TITLE
Fix: can't build Broker image anymore

### PR DESCRIPTION
**Pull request by ysbaddaden**

### CODE REVIEW

**Review by matiasgarciaisaia — APPROVED** [review]
Simply awesome! 🎉 

I've triggered [this Action](https://github.com/instedd/verboice/actions/runs/2097773180) to check the build actually works in the CI 👍

Just for reference, the current `rebar` `master` version on top of which to apply the patch is https://github.com/rebar/rebar/tree/b6d309417c502ca243f810e5313bea36951ef038

**Comment by ysbaddaden** [comment]
@matiasgarciaisaia Maybe we should fork `rebar/rebar` as `manastech/rebar` and add the patch to it, so we won't lose or forget it.

**Comment by matiasgarciaisaia** [comment]
@ysbaddaden That's an option, sure.

Do you know if migrating to a supported rebar version (rebar3?) implies much more effort?

**Comment by ysbaddaden** [comment]
We should ask @ggiraldez about that. Reading https://rebar3.org/docs/tutorials/from_rebar2_to_rebar3/ it seems not too hard but non trivial (for non Erlang developers such as me). It seems migrating to rebar3 means migrating to [hex.pm](https://hex.pm)?

**Comment by matiasgarciaisaia** [comment]
I'll merge this one, we can then decide what to do regarding a long-term solution to rebar.

**Pull request merged**
